// src/page-builder/SectionDistributor.vue
<template>
  <component
    :is="fullWidthModuleMap[module.type]"
    v-if="section.type === 'full-width' && module"
    :module="module"
  />
  <template v-else-if="section.type === 'regular'">
    Regular section
  </template>
</template>

<script setup lang="ts">
import FullWidthCarouselModule from '../modules/FullWidthCarouselModule.vue'
import FullWidthImageModule from '../modules/FullWidthImageModule.vue'
import FullWidthHeaderModule from '../modules/FullWidthHeaderModule.vue'

const props = defineProps<{
  section: UI.Section
}>()

const module = $ref<UI.FullWidthModule | null>('module' in props.section ? props.section.module : null)

const fullWidthModuleMap: Record<UI.FullWidthModule['type'], unknown> = {
  'full-width-header': FullWidthHeaderModule,
  'full-width-image': FullWidthImageModule,
  'full-width-carousel': FullWidthCarouselModule,
}
</script>

// src/page-builder/SectionDistributor.svelte
<template>
  {#if section.type === 'full-width'}
    <svelte:component this={fullwidthModuleMap[module.type]} {module} />
  {:else if section.type === 'regular'}
    Regular section
  {/if}
</template>

<script lang="ts">
import FullWidthCarouselModule from '../modules/FullWidthCarouselModule.svelte'
import FullWidthImageModule from '../modules/FullWidthImageModule.svelte'
import FullWidthHeaderModule from '../modules/FullWidthHeaderModule.svelte'

export let section: UI.Section
const module = section['module']

const fullwidthModuleMap: Record<UI.FullWidthModule['type'], unknown> = {
  'full-width-header': FullWidthHeaderModule,
  'full-width-image': FullWidthImageModule,
  'full-width-carousel': FullWidthCarouselModule,
}
</script>
