// src/page-builder/PageBuilder.vue
<template>
  <div class="page-builder" :spellcheck="false">
    <TransitionGroup
      tag="div"
      name="flip"
      class="section-container"
      @dragover="onDragOver"
    >
      <section
        v-for="section in pageConfig.sections"
        :id="`section-${section.id}`"
        :key="section.id"
        @mouseenter="onSelectSection(section)"
      >
        <SectionDistributor v-if="section.type === 'full-width'" :section="section" />
      </section>
    </TransitionGroup>

    <SectionOperator @dragend="onDragEnd" @dragstart="onDragStart" />
  </div>
</template>

<script setup lang="ts">
import examplePageConfig from 'src/examplePageConfig'
import SectionDistributor from 'src/page-builder/SectionDistributor.vue'
import SectionOperator from 'src/page-builder/SectionOperator.vue'
import { currentDragOverSection, currentDragSection, currentSection, sectionModal } from 'src/stores/pageBuilder'
import { pageConfig } from 'src/stores/pageConfig'
import { onMounted } from 'vue'
import { throttle } from 'src/utils'

pageConfig.value = examplePageConfig

onMounted(() => {
  document.addEventListener('dragover', e => e.preventDefault())
})

function onSelectSection (section: UI.Section) {
  if (sectionModal.value) return
  currentSection.value = section
}

function onDragStart (section: UI.Section) {
  const index = pageConfig.value.sections.findIndex(it => it === section)
  currentDragSection.value = pageConfig.value.sections[index]
  currentSection.value = null
  pageConfig.value.sections.splice(index, 1)
}

function onDragEnd () {
  let insertIndex = pageConfig.value.sections.findIndex(it => it.id === currentDragOverSection.value.section?.id)
  if (!currentDragOverSection.value.isTop) insertIndex += 1
  pageConfig.value.sections.splice(insertIndex, 0, currentDragSection.value!)
  currentDragSection.value = null
}

const onDragOver = throttle(function (event: DragEvent) {
  const sectionElement = (event.target as HTMLElement)?.closest('section')
  if (!sectionElement) return
  event.stopPropagation()
  const topThreshold = sectionElement.offsetTop + sectionElement.offsetHeight / 2
  const isTop = event.clientY < topThreshold
  const sectionId = sectionElement?.id.replace(/^section-/, '')
  const section = pageConfig.value.sections.find(it => it.id === sectionId) ?? null
  currentDragOverSection.value = ({ section, isTop })
}, 100)
</script>

<style lang="scss">
.page-builder {
  position: relative;
}

.flip-move,
.flip-enter-active,
.flip-leave-active {
  transition: all 0.4s ease;
}

.flip-enter-from,
.flip-leave-to {
  opacity: 0;
}

.flip-leave-active {
  position: absolute;
  left: 0;
  right: 0;
}
</style>

// src/components/PageBuilder.svelte
<template>
  <div class="page-builder" spellcheck={false}>
    <div class="section-container" on:dragover={throttle(onDragOver, 100)}>
      {#each $pageConfig.sections as section (section.id)}
        <section
          id="section-{section.id}"
          animate:flip={{duration: d => Math.sqrt(d) * 10, delay: 100}}
          on:mouseenter={() => onSelectSection(section)}
        >
          {#if section.type === 'full-width'}
            <FullWidthSection {section} />
          {/if}
        </section>
      {/each}
    </div>

    <SectionOperator on:dragend={onDragEnd} on:dragstart={onDragStart} />
  </div>
</template>

<script lang="ts">
import { onMount } from 'svelte'
import { flip } from 'svelte/animate'
import examplePageConfig from '../examplePageConfig'
import { currentDragOverSection, currentDragSection, currentSection, sectionModal } from '../stores/currentSection'
import { pageConfig } from '../stores/pageConfig'
import SectionOperator from './SectionOperator.svelte'
import FullWidthSection from './FullWidthSection.svelte'
import { throttle } from '../utils'

pageConfig.set(examplePageConfig)

onMount(() => {
  document.addEventListener('dragover', e => void e.preventDefault())
})

function onSelectSection(section: UI.Section) {
  if ($sectionModal) return
  currentSection.set(section)
}

function onDragStart(event: CustomEvent<UI.Section>) {
  const index = $pageConfig.sections.findIndex((it => it === event.detail))
  currentDragSection.set($pageConfig.sections[index])
  currentSection.set(null)
  pageConfig.update(config => {
    config.sections.splice(index, 1)
    return config
  })
}

function onDragEnd(event: CustomEvent) {
  event.preventDefault()

  let insertIndex = $pageConfig.sections.findIndex(it => it.id === $currentDragOverSection.section.id)
  if (!$currentDragOverSection.isTop) insertIndex += 1
  pageConfig.update(config => {
    config.sections.splice(insertIndex, 0, $currentDragSection)
    return config
  })
  currentDragSection.set(null)
}

function onDragOver(event: DragEvent) {
  const sectionElement = (event.target as HTMLElement)?.closest('section')
  if (!sectionElement) return
  const topThreshold = sectionElement.offsetTop + sectionElement.offsetHeight / 2
  const isTop = event.clientY < topThreshold
  const sectionId = sectionElement?.id.replace(/^section-/, '')
  const section = $pageConfig.sections.find(it => it.id === sectionId) ?? null
  currentDragOverSection.set({ section, isTop })
}
</script>

<style lang="scss">
.page-builder {
  position: relative;
}
</style>
